Cmake is implemented (but make still available).
Only two changes in source files:
1- <sml_root>/Makefile for handling the move of test/ft/unit*.cpp files to the newest test/unit folder.
2- ";" removed at <sml_root>sml/benchmark/complex/sml.cpp:237:2: error: extra ‘;’ [-Wpedantic]

Tested with gcc-6.3.0/gcc-7.2.0/VS-2015/VS-2017
Some targets are disabled, mainly for VS-2015, they are defined in CMakeLists.txt but commented.
All executable targets are launched with ctest command, ctest is installed with cmake.

Cmake survival kit copied from <sml_root>/CMakeLists.txt:
# Generate stage:
#   $mkdirBUILD; cd BUILD; cmake ..
#   Re-generate after changes:
#     $cmake .
#   Show each build command line as it is launched
#   $cmake -DCMAKE_VERBOSE_MAKEFILE=ON ..
#   Generate a release version: $cmake -DCMAKE_BUILD_TYPE=Release ..

# Build stage:
#   Linux: $cmake --build . -- -j
#   Windows: $cmake --build . -- /maxcpucount
#   Build only test/action_defer:
#   $cmake --build . --target actions_defer

# Test stage:
#    Launch all tests: $ctest --verbose
#    To run tests with memcheck: $ctest -T memcheck
#    List available test: $ctest -N
#    Launch benchmark tests: $ctest -R benchmark*

Contained in no branch
Contained in no tag

Contained in branches: cmake_implemented
Contained in no tag